[phases.setup]
nixPkgs = ["...", "ffmpeg", "pkg-config"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install setuptools wheel", "pip install -r requirements.txt"]
