[phases.setup]
nixPkgs = ["...", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install -r requirements.txt"
]
